# Generated by Django 4.2.13 on 2024-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_category',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
