# Generated by Django 4.2.13 on 2024-06-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_is_active'),
        ('card_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='card',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
