# Generated by Django 4.2.13 on 2024-06-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_digits',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='FuelTransactions',
        ),
    ]
