# Generated by Django 4.2.13 on 2024-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_management', '0002_alter_card_company_alter_card_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddriverhistory',
            name='beg_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carddriverhistory',
            name='card',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='carddriverhistory',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
