# Generated by Django 4.2.13 on 2024-07-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_management', '0001_initial'),
        ('card_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('client_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('company_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quantity', models.FloatField()),
                ('retail_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('client_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('company_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('item', models.CharField(max_length=100)),
                ('client_profit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('company_profit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('transaction_fee', models.FloatField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_management.card')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_management.store')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
