# Generated by Django 4.2.13 on 2024-06-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_management', '0002_storeprice_company_price'),
        ('card_management', '0003_card_last_digits_delete_fueltransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('retail_price', models.FloatField()),
                ('client_price', models.FloatField()),
                ('company_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('retail_amount', models.FloatField()),
                ('client_amount', models.FloatField()),
                ('company_amount', models.FloatField()),
                ('item', models.CharField(max_length=100)),
                ('client_profit', models.FloatField()),
                ('company_profit', models.FloatField()),
                ('transaction_fee', models.FloatField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_management.card')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_management.store')),
            ],
        ),
    ]
