# Generated by Django 4.2.13 on 2024-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
