# Generated by Django 4.2.13 on 2024-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_client_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
