# Generated by Django 4.2.13 on 2024-06-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_transaction_paid_transaction_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'time']},
        ),
        migrations.DeleteModel(
            name='TransactionPayment',
        ),
    ]
