# Generated by Django 4.2.13 on 2024-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_management', '0002_storeprice_company_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
