# Generated by Django 4.2.13 on 2024-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_management', '0003_store_lattitude_store_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=20),
        ),
    ]
