# Generated by Django 4.2.13 on 2024-06-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_management', '0004_alter_store_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
