# Generated by Django 4.2.13 on 2024-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_management', '0007_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprice',
            name='company_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
