# Generated by Django 4.2.13 on 2024-06-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_management', '0008_alter_storeprice_company_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprice',
            name='company_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='price_5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
